### ISSUE TITLE
Iterative Improvements of Mecanum Drive

### ISSUE THREAD

**Issue by gavinjalberghini** [Team2890HawkCollective/Training#86]
Description: Once you have an initial draft of the robot code working with mecanum. The next task is to iteratively add more features, sensors, and manipulators that are commonly used on the robot. 

Acceptance Criteria:
- You have a working drive code for a mecanum chassis with configurable joystick dead zones, speed coefficients, and polarity modifiers
- You have gyro information (roll, pitch, yaw and x, y, z acceleration) graphed to the smart dashboard
- You have an autonomous program for the robot to drive forward for 5 seconds and then turn 90 degrees to the left or right based on shuffleboard input
- You have a USB camera display up on the smart dashboard with a custom hit marker cursor in the center of the screen 
- You have a servo attached to the drive train subsystem that articulates open on RB and closed on LB
- You have a rangefinder that displays information to the smart dashboard

**Comment by Jacoby-Powell** [comment]
Gyro and Autonomous are both completed. They just need testing, which requires us to find the NavX first.
